### ISSUE TITLE
Componetize the application

### ISSUE THREAD

**Issue by RRoggia** [RRoggia/techschool-network#3]
**Subtasks:**
- [ ] Use of `ComponentContainer` in the `index.html`
- [ ] Create a `Component.js` file under `webapp` folder
- [ ] Use the `metadata` attribute to instantiate the `Feed.view.xml`

**Resources:**
[Component Configuration](https://sapui5.hana.ondemand.com/#/topic/4cfa60872dca462cb87148ccd0d948ee)

**Need Help?**
[My Implementation](https://github.com/RRoggia/techschool-network/commit/8e2e5a350f9606cbb597981bc36245a62824612e)

**Comment by gaazamba** [comment]
Done.
