### ISSUE TITLE
Add App and Pages with a title to the application

### ISSUE THREAD

**Issue by RRoggia** [RRoggia/techschool-network#7]
**Subtasks:**
- [ ] Add an `App` to the view
- [ ] Add a `Page` to the view
- [ ] Add The text to the `title` attribute of the `Page`

**Resources:**
[App and Pages](https://sapui5.hana.ondemand.com/#/topic/3b9d9f84930d43df90ad0789d99bd4a3)

**Need Help?**
[My implementation](https://github.com/RRoggia/techschool-network/commit/af8da82b47dec82d48f5e16b43551fdf3ec207c6)

**Comment by gaazamba** [comment]
Done.
