### ISSUE TITLE
Enable posting feedbacks and to read the feedbacks

### ISSUE THREAD

**Issue by RRoggia** [RRoggia/techschool-network#9]
**Subtasks:**
- [ ] add a `FeedInput` to the `Feed.view.xml`
- [ ] Initialize a model for the feedbacks in the `Feed.controller.js` initialization
- [ ] Add the feedback to the model using the `post` event of the `FeedInput`
- [ ] Add a `FeedList` to the `Feed.view.xml` and bind it with the feedbacks model

**Resources:**
[FeedInput](https://sapui5.hana.ondemand.com/#/entity/sap.m.FeedInput)
[FeedListItem](https://sapui5.hana.ondemand.com/#/sample/sap.m.sample.FeedListItem)

**Need Help?**
[My Implementation](https://github.com/RRoggia/techschool-network/tree/add-feedback)
